#spring:
#  mvc:
#    view:
#      prefix: /jsp/
#      suffix: .jsp
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/dapeng_test?serverTimezone=UTC
#    username: test
#    password: 123456
#    filters: stat,wall
#    maxActive: 20
##    minIdle: 5
#    initialSize: 1
#    maxWait: 60000
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=5000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 1 from dual
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    logSlowSql: true
#  jpa:
#     properties:
#       hibernate:
#         show_sql: true
#         format_sql: true