#spring.mvc.view.prefix=/jsp/
#spring.mvc.view.suffix=.jsp

##使用yml文件，value冒号后一定要带空格；2，时区要设置在url后
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dapeng_test?serverTimezone=UTC
#    driverClassName: com.mysql.jdbc.Driver
    username: test
    password: 123456
#配置监控统计拦截的filters,去掉后监控界面sql无法统计，'wall'用于防火
    filters: stat,wall
#最大活跃数
    maxActive: 20
    minIdle: 5
#初始化数量
    initialSize: 1
#最大连接等待的超时时间
    maxWait: 60000
#打开PSCache,并指定每个PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
#通过connectionProperties属性打开mergeSql功能；慢sql记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=5000
    minldle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    logSlowSql: true
#  jpa:
#    database: MYSQL
#    show-sql: true
#    hibernate:
#    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy'
  jpa:
     properties:
       hibernate:
         show_sql: true
         format_sql: true


#spring.datasource.url=jdbc:mysql://localhost:3306/dapeng_test?serverTimezone=UTC
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.username=test
#spring.datasource.password=123456
#
#spring.jpa.database=MYSQL
#spring.jpa.show-sql=true
#spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy


#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect